//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamcoForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerShipAddress { get; set; }
        public string CustomerBillAddress { get; set; }
        public string CustomerBillCity { get; set; }
        public string CustomerShipCity { get; set; }
        public string CustomerBillZipCode { get; set; }
        public string CustomerShipZipCode { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerFax { get; set; }
        public string CustomerBillState { get; set; }
        public string CustomerShipState { get; set; }
        public string AccountNo { get; set; }
    }
}
