//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamcoForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        public int KitID { get; set; }
        public string Kit_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Sales_Price { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
    }
}
