//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamcoForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLineItem
    {
        public int PurchaseID { get; set; }
        public string PurchaseSO { get; set; }
        public string PurchasePO { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> ProductExtension { get; set; }
        public Nullable<decimal> PurchaseTotal { get; set; }
        public Nullable<int> ProductNo { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> VendorID { get; set; }
    }
}
