//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamcoForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Received
    {
        public int ReceivedID { get; set; }
        public string PurchaseSO { get; set; }
        public string PurchasePO { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> QuantityReceived { get; set; }
        public Nullable<int> QuantityRemaining { get; set; }
        public Nullable<System.DateTime> DateScheduled { get; set; }
        public Nullable<bool> PackingList { get; set; }
    }
}
