//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamcoForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int ShipID { get; set; }
        public Nullable<int> InvoiceSO { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> QuantityPicked { get; set; }
        public Nullable<int> QuantityRemaining { get; set; }
        public string DateScheduled { get; set; }
        public Nullable<bool> PackingList { get; set; }
        public string InvoicePO { get; set; }
        public string ProductDescription { get; set; }
    }
}
