
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CamcoForm
{

using System;
    using System.Collections.Generic;
    
public partial class Vendor
{

    public int VendorID { get; set; }

    public string VendorName { get; set; }

    public string VendorAddress { get; set; }

    public string VendorCity { get; set; }

    public string VendorState { get; set; }

    public string VendorZip { get; set; }

    public string VendorPhone { get; set; }

}

}
